#!/usr/bin/env php
<?php
/**
 * Jamilx CLI entrypoint that boots the console kernel.
 */
$rootPath = __DIR__;

require_once $rootPath . '/console/JX_ConsoleAutoload.php';
JX_ConsoleAutoload::register($rootPath . '/console');

require_once $rootPath . '/console/JX_ConsoleKernel.php';
$kernel = new JX_ConsoleKernel($rootPath);

exit($kernel->handle($argv));
