<?php 
return [
    'up' => [
        "CREATE TABLE IF NOT EXISTS `invoice_clients` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `user_id` INT NULL,
            `name` VARCHAR(150) NOT NULL,
            `company` VARCHAR(150) NULL,
            `email` VARCHAR(150) NULL,
            `phone` VARCHAR(50) NULL,
            `address` TEXT NULL,
            `created_at` DATETIME NOT NULL,
            `updated_at` DATETIME NOT NULL,
            `deleted_at` DATETIME NULL,
            INDEX (`user_id`),
            INDEX (`email`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `invoice_settings` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `prefix` VARCHAR(20) NOT NULL,
            `next_number` INT NOT NULL,
            `created_at` DATETIME NOT NULL,
            `updated_at` DATETIME NOT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `invoices` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `client_id` INT NOT NULL,
            `invoice_number` VARCHAR(50) NOT NULL,
            `status` VARCHAR(30) NOT NULL,
            `issue_date` DATE NOT NULL,
            `due_date` DATE NULL,
            `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `tax_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `discount_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `total` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `amount_paid` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `balance_due` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `notes` TEXT NULL,
            `created_by` INT NOT NULL,
            `created_at` DATETIME NOT NULL,
            `updated_at` DATETIME NOT NULL,
            `deleted_at` DATETIME NULL,
            INDEX (`client_id`),
            INDEX (`status`),
            INDEX (`invoice_number`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `invoice_items` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `invoice_id` INT NOT NULL,
            `description` VARCHAR(255) NOT NULL,
            `quantity` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `discount` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `tax` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `line_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `created_at` DATETIME NOT NULL,
            INDEX (`invoice_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `payments` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `invoice_id` INT NOT NULL,
            `amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `method` VARCHAR(50) NOT NULL,
            `notes` TEXT NULL,
            `refunded_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
            `refund_notes` TEXT NULL,
            `refunded_at` DATETIME NULL,
            `created_by` INT NOT NULL,
            `created_at` DATETIME NOT NULL,
            INDEX (`invoice_id`),
            INDEX (`method`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `forum_categories` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `name` VARCHAR(150) NOT NULL,
            `slug` VARCHAR(150) NOT NULL,
            `description` TEXT NULL,
            `position` INT NOT NULL DEFAULT 0,
            `is_active` TINYINT(1) NOT NULL DEFAULT 1,
            `created_at` DATETIME NOT NULL,
            `updated_at` DATETIME NOT NULL,
            UNIQUE KEY (`slug`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `forum_topics` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `category_id` INT NOT NULL,
            `user_id` INT NOT NULL,
            `title` VARCHAR(200) NOT NULL,
            `slug` VARCHAR(200) NOT NULL,
            `is_locked` TINYINT(1) NOT NULL DEFAULT 0,
            `is_pinned` TINYINT(1) NOT NULL DEFAULT 0,
            `reply_count` INT NOT NULL DEFAULT 0,
            `last_post_at` DATETIME NOT NULL,
            `created_at` DATETIME NOT NULL,
            `updated_at` DATETIME NOT NULL,
            `deleted_at` DATETIME NULL,
            INDEX (`category_id`),
            INDEX (`user_id`),
            INDEX (`slug`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `forum_posts` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `topic_id` INT NOT NULL,
            `user_id` INT NOT NULL,
            `body` TEXT NOT NULL,
            `created_at` DATETIME NOT NULL,
            `updated_at` DATETIME NOT NULL,
            `deleted_at` DATETIME NULL,
            INDEX (`topic_id`),
            INDEX (`user_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS `forum_post_edits` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `post_id` INT NOT NULL,
            `editor_id` INT NOT NULL,
            `previous_body` TEXT NOT NULL,
            `created_at` DATETIME NOT NULL,
            INDEX (`post_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    ],
    'down' => [
        "DROP TABLE IF EXISTS `forum_post_edits`",
        "DROP TABLE IF EXISTS `forum_posts`",
        "DROP TABLE IF EXISTS `forum_topics`",
        "DROP TABLE IF EXISTS `forum_categories`",
        "DROP TABLE IF EXISTS `payments`",
        "DROP TABLE IF EXISTS `invoice_items`",
        "DROP TABLE IF EXISTS `invoices`",
        "DROP TABLE IF EXISTS `invoice_settings`",
        "DROP TABLE IF EXISTS `invoice_clients`",
    ],
];
